server:
  port: 8084

spring:
  application:
    name: riffy
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
